# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - arm_controller
    # - hand_controller

  arm_controller:
    type: FollowJointTrajectory
    joints:
      - servo_1
      - servo_2
      - servo_3
      - servo_4
      - servo_5
      - servo_6
      - servo_7
      - servo_8
    action_ns: follow_joint_trajectory
    default: true
  # hand_controller:
  #   type: FollowJointTrajectory
  #   joints:
  #     - servo_8
  #   action_ns: follow_joint_trajectory
  #   default: true